# BSD 3-Clause License
# Copyright (c) 2026, UChicago Argonne, LLC, Argonne National Laboratory.
# Adapted from annual-report/annual_report/sidecar.py and extract_publication_stub_one.py
"""bib.yaml read/write with per-field provenance merge."""
from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from .io import atomic_write_text, now_iso, sha256_file


_SOURCE_PRIORITY: dict[str, int] = {
    "human":          100,
    "osti":            80,
    "openalex":        70,
    "crossref":        65,
    "dblp":            60,
    "bibtex":          55,
    "arxiv":           50,
    "pdf":             30,
    "llm":             20,
    "semanticscholar": 15,
    "derived":         10,
    "unknown":          0,
}

_CATEGORY_VALUES = {
    "journal article",
    "conference paper",
    "workshop paper",
    "arxiv preprint",
    "preprint",
    "book chapter",
    "book",
    "technical report",
    "thesis",
    "other",
}

_ALL_FIELDS = [
    "title", "authors", "year", "publication_date", "venue", "venue_short",
    "category", "doi", "arxiv_id", "osti_id", "isbn", "issn", "url",
    "abstract", "bibtex_key", "keywords", "language", "license", "oa_status",
    "references_count", "pages",
]


def priority(source: str) -> int:
    return _SOURCE_PRIORITY.get(source, 0)


def make_prov(
    source: str,
    lookup_key: str | None = None,
    similarity: float | None = None,
    note: str | None = None,
) -> dict[str, Any]:
    p: dict[str, Any] = {"source": source, "lookup_key": lookup_key, "at": now_iso()}
    if similarity is not None:
        p["similarity"] = round(similarity, 4)
    if note is not None:
        p["note"] = note
    return p


def set_field(
    fields: dict[str, Any],
    prov: dict[str, Any],
    field: str,
    value: Any,
    source: str,
    lookup_key: str | None = None,
    similarity: float | None = None,
    note: str | None = None,
) -> bool:
    """Set fields[field] if source has strictly higher priority than current. Returns True if updated."""
    if value is None or value == [] or value == "":
        return False
    if field == "category" and value not in _CATEGORY_VALUES:
        return False
    current_source = prov.get(field, {}).get("source", "unknown")
    if field not in prov or priority(source) >= priority(current_source):
        if prov.get(field, {}).get("source") == "human":
            return False
        fields[field] = value
        prov[field] = make_prov(source, lookup_key, similarity, note)
        return True
    return False


def bib_path(analysis_dir: Path) -> Path:
    return analysis_dir / "bib.yaml"


def load_bib(analysis_dir: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    """Load bib.yaml. Returns (fields, provenance). Both dicts are empty if file absent."""
    p = bib_path(analysis_dir)
    if not p.exists():
        return {}, {}
    raw = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    prov = raw.pop("_provenance", {}) or {}
    raw.pop("_conflicts", None)
    raw.pop("_lookup_log", None)
    raw.pop("_meta", None)
    return raw, prov


def save_bib(
    analysis_dir: Path,
    pdf_path: Path,
    fields: dict[str, Any],
    prov: dict[str, Any],
    lookup_log: dict[str, Any],
    conflicts: dict[str, Any],
    tool_version: str,
    prompt_version: str,
) -> None:
    from . import __version__

    pdf_sha = sha256_file(pdf_path)

    ordered: dict[str, Any] = {}
    for f in _ALL_FIELDS:
        ordered[f] = fields.get(f)

    ordered["needs_review"] = bool(conflicts)
    ordered["notes"] = fields.get("notes", "")

    ordered["_provenance"] = prov

    if conflicts:
        ordered["_conflicts"] = conflicts

    ordered["_lookup_log"] = lookup_log

    ordered["_meta"] = {
        "schema_version": 1,
        "tool_version": tool_version,
        "prompt_version": prompt_version,
        "generated_at": now_iso(),
        "pdf_sha256": pdf_sha,
    }

    log_lines = []
    for src, info in lookup_log.items():
        status = info.get("status", "?")
        sim = info.get("sim")
        sim_str = f" sim={sim:.2f}" if sim is not None else ""
        key = info.get("key", "")
        reason = info.get("reason", "")
        if reason:
            log_lines.append(f"#   {src:<18} {status}  {reason}")
        else:
            log_lines.append(f"#   {src:<18} {status}  {key}{sim_str}")

    header = "\n".join([
        f"# Generated by puba bib on {now_iso()}",
        f"# Source PDF: {pdf_path.name}  sha256:{pdf_sha[:12]}...",
        "# Lookup status:",
        *log_lines,
        "#",
        "# Fields with _provenance.<field>.source: human are sticky and will not be",
        "# overwritten by future runs. Edit freely; re-run puba bib to refresh.",
        "",
        "",
    ])

    body = yaml.dump(ordered, allow_unicode=True, sort_keys=False, default_flow_style=False)
    atomic_write_text(bib_path(analysis_dir), header + body)


def load(pdf_path: Path) -> dict[str, Any]:
    """Public API: load the full bib.yaml for a paper as a flat dict."""
    from .state import analysis_dir as get_analysis_dir
    d = get_analysis_dir(pdf_path)
    p = bib_path(d)
    if not p.exists():
        return {}
    return yaml.safe_load(p.read_text(encoding="utf-8")) or {}
