# BSD 3-Clause License
# Copyright (c) 2026, UChicago Argonne, LLC, Argonne National Laboratory.
"""Unit tests for the JSON-capable artifact I/O compatibility layer (Milestone 1).

These tests exercise puba.artifacts in isolation against synthetic fixtures
and do NOT require network access, GPU, or a running LLM.
"""
from __future__ import annotations

import json
import warnings
from pathlib import Path
from typing import Any

import pytest
import yaml

from puba.artifacts import (
    BothFormsPresentWarning,
    bib_json_path,
    bib_yaml_path,
    distill_json_path,
    distill_yaml_path,
    list_distill_names,
    read_bib,
    read_distill,
    write_bib,
    write_distill,
)


# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------

_SAMPLE_BIB: dict[str, Any] = {
    "title": "Test Paper",
    "authors": ["Alice Smith"],
    "year": 2026,
    "abstract": "A concise abstract.",
    "needs_review": False,
}

_SAMPLE_DISTILL: dict[str, Any] = {
    "name": "summary",
    "scope": "abstract",
    "model": "test-model",
    "generated_at": "2026-01-01T00:00:00+00:00",
    "output": "This paper studies X.",
}


def _write_yaml(path: Path, data: dict, header: str = "") -> None:
    """Helper: write a dict as YAML (optionally with a comment header)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False)
    path.write_text(header + body, encoding="utf-8")


def _write_json(path: Path, data: dict) -> None:
    """Helper: write a dict as JSON."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def _make_analysis_dir(tmp_path: Path) -> Path:
    ad = tmp_path / "paper.puba"
    ad.mkdir()
    return ad


# ===========================================================================
# Path helpers
# ===========================================================================


class TestPathHelpers:

    def test_bib_json_path(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        assert bib_json_path(ad) == ad / "bib.json"

    def test_bib_yaml_path(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        assert bib_yaml_path(ad) == ad / "bib.yaml"

    def test_distill_json_path(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        assert distill_json_path(ad, "summary") == ad / "analyses" / "summary.json"

    def test_distill_yaml_path(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        assert distill_yaml_path(ad, "summary") == ad / "analyses" / "summary.yaml"


# ===========================================================================
# read_bib
# ===========================================================================


class TestReadBib:

    # -----------------------------------------------------------------------
    # Legacy YAML only
    # -----------------------------------------------------------------------

    def test_reads_yaml_when_only_yaml_present(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "bib.yaml", _SAMPLE_BIB)
        result = read_bib(ad)
        assert result is not None
        assert result["title"] == "Test Paper"
        assert result["year"] == 2026

    def test_yaml_only_does_not_warn(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "bib.yaml", _SAMPLE_BIB)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            read_bib(ad)
        bfp_warnings = [w for w in caught if issubclass(w.category, BothFormsPresentWarning)]
        assert not bfp_warnings

    def test_yaml_with_header_comments_parsed(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        header = "# Generated by puba bib on 2026-01-01T00:00:00+00:00\n#\n\n"
        _write_yaml(ad / "bib.yaml", _SAMPLE_BIB, header=header)
        result = read_bib(ad)
        assert result is not None
        assert result["title"] == "Test Paper"

    def test_yaml_empty_file_returns_empty_dict(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        (ad / "bib.yaml").write_text("", encoding="utf-8")
        result = read_bib(ad)
        # yaml.safe_load of empty string is None; we normalise to {}
        assert result == {}

    # -----------------------------------------------------------------------
    # New JSON only
    # -----------------------------------------------------------------------

    def test_reads_json_when_only_json_present(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_json(ad / "bib.json", _SAMPLE_BIB)
        result = read_bib(ad)
        assert result is not None
        assert result["title"] == "Test Paper"

    def test_json_only_does_not_warn(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_json(ad / "bib.json", _SAMPLE_BIB)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            read_bib(ad)
        bfp_warnings = [w for w in caught if issubclass(w.category, BothFormsPresentWarning)]
        assert not bfp_warnings

    def test_json_roundtrip_preserves_types(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        data = {**_SAMPLE_BIB, "nested": {"key": [1, 2, 3]}, "needs_review": True}
        _write_json(ad / "bib.json", data)
        result = read_bib(ad)
        assert result is not None
        assert result["nested"] == {"key": [1, 2, 3]}
        assert result["needs_review"] is True

    # -----------------------------------------------------------------------
    # Both present
    # -----------------------------------------------------------------------

    def test_json_wins_when_both_present(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        yaml_data = {**_SAMPLE_BIB, "title": "YAML Version"}
        json_data = {**_SAMPLE_BIB, "title": "JSON Version"}
        _write_yaml(ad / "bib.yaml", yaml_data)
        _write_json(ad / "bib.json", json_data)
        result = read_bib(ad)
        assert result is not None
        assert result["title"] == "JSON Version"

    def test_both_present_emits_warning(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "bib.yaml", _SAMPLE_BIB)
        _write_json(ad / "bib.json", _SAMPLE_BIB)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            read_bib(ad)
        bfp_warnings = [w for w in caught if issubclass(w.category, BothFormsPresentWarning)]
        assert len(bfp_warnings) == 1

    def test_warning_references_correct_paths(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "bib.yaml", _SAMPLE_BIB)
        _write_json(ad / "bib.json", _SAMPLE_BIB)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            read_bib(ad)
        w = next(x for x in caught if issubclass(x.category, BothFormsPresentWarning))
        instance: BothFormsPresentWarning = w.message  # type: ignore[assignment]
        assert instance.json_path == ad / "bib.json"
        assert instance.yaml_path == ad / "bib.yaml"

    def test_warning_message_is_informative(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "bib.yaml", _SAMPLE_BIB)
        _write_json(ad / "bib.json", _SAMPLE_BIB)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            read_bib(ad)
        w = next(x for x in caught if issubclass(x.category, BothFormsPresentWarning))
        msg = str(w.message)
        assert "bib.json" in msg
        assert "bib.yaml" in msg
        assert "stale" in msg.lower() or "authoritative" in msg.lower()

    # -----------------------------------------------------------------------
    # Neither present
    # -----------------------------------------------------------------------

    def test_returns_none_when_neither_present(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        result = read_bib(ad)
        assert result is None


# ===========================================================================
# read_distill
# ===========================================================================


class TestReadDistill:

    # -----------------------------------------------------------------------
    # Legacy YAML only
    # -----------------------------------------------------------------------

    def test_reads_yaml_when_only_yaml_present(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "analyses" / "summary.yaml", _SAMPLE_DISTILL)
        result = read_distill(ad, "summary")
        assert result is not None
        assert result["output"] == "This paper studies X."

    def test_yaml_only_does_not_warn(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "analyses" / "summary.yaml", _SAMPLE_DISTILL)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            read_distill(ad, "summary")
        bfp_warnings = [w for w in caught if issubclass(w.category, BothFormsPresentWarning)]
        assert not bfp_warnings

    def test_yaml_with_header_comments_parsed(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        header = "# puba distill — summary\n# generated_at: 2026-01-01T00:00:00+00:00\n\n"
        _write_yaml(ad / "analyses" / "summary.yaml", _SAMPLE_DISTILL, header=header)
        result = read_distill(ad, "summary")
        assert result is not None
        assert result["name"] == "summary"

    # -----------------------------------------------------------------------
    # New JSON only
    # -----------------------------------------------------------------------

    def test_reads_json_when_only_json_present(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_json(ad / "analyses" / "summary.json", _SAMPLE_DISTILL)
        result = read_distill(ad, "summary")
        assert result is not None
        assert result["scope"] == "abstract"

    def test_json_only_does_not_warn(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_json(ad / "analyses" / "summary.json", _SAMPLE_DISTILL)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            read_distill(ad, "summary")
        bfp_warnings = [w for w in caught if issubclass(w.category, BothFormsPresentWarning)]
        assert not bfp_warnings

    def test_json_roundtrip_preserves_types(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        data = {**_SAMPLE_DISTILL, "evidence": [{"quote": "X", "verified": True}]}
        _write_json(ad / "analyses" / "summary.json", data)
        result = read_distill(ad, "summary")
        assert result is not None
        assert result["evidence"][0]["verified"] is True

    # -----------------------------------------------------------------------
    # Both present
    # -----------------------------------------------------------------------

    def test_json_wins_when_both_present(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        yaml_data = {**_SAMPLE_DISTILL, "output": "YAML output"}
        json_data = {**_SAMPLE_DISTILL, "output": "JSON output"}
        _write_yaml(ad / "analyses" / "summary.yaml", yaml_data)
        _write_json(ad / "analyses" / "summary.json", json_data)
        result = read_distill(ad, "summary")
        assert result is not None
        assert result["output"] == "JSON output"

    def test_both_present_emits_warning(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "analyses" / "summary.yaml", _SAMPLE_DISTILL)
        _write_json(ad / "analyses" / "summary.json", _SAMPLE_DISTILL)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            read_distill(ad, "summary")
        bfp_warnings = [w for w in caught if issubclass(w.category, BothFormsPresentWarning)]
        assert len(bfp_warnings) == 1

    def test_warning_references_correct_paths(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "analyses" / "summary.yaml", _SAMPLE_DISTILL)
        _write_json(ad / "analyses" / "summary.json", _SAMPLE_DISTILL)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            read_distill(ad, "summary")
        w = next(x for x in caught if issubclass(x.category, BothFormsPresentWarning))
        instance: BothFormsPresentWarning = w.message  # type: ignore[assignment]
        assert instance.json_path == ad / "analyses" / "summary.json"
        assert instance.yaml_path == ad / "analyses" / "summary.yaml"

    def test_different_names_independent(self, tmp_path):
        """Two distillation names with one having both formats do not interfere."""
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "analyses" / "summary.yaml", _SAMPLE_DISTILL)
        _write_json(ad / "analyses" / "detail.json", {**_SAMPLE_DISTILL, "name": "detail"})
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            r1 = read_distill(ad, "summary")
            r2 = read_distill(ad, "detail")
        bfp_warnings = [w for w in caught if issubclass(w.category, BothFormsPresentWarning)]
        assert not bfp_warnings
        assert r1 is not None and r1["name"] == "summary"
        assert r2 is not None and r2["name"] == "detail"

    # -----------------------------------------------------------------------
    # Neither present
    # -----------------------------------------------------------------------

    def test_returns_none_when_neither_present(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        result = read_distill(ad, "summary")
        assert result is None


# ===========================================================================
# write_bib
# ===========================================================================


class TestWriteBib:

    def test_write_yaml_creates_bib_yaml(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        path = write_bib(ad, _SAMPLE_BIB, fmt="yaml")
        assert path == ad / "bib.yaml"
        assert path.exists()

    def test_write_json_creates_bib_json(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        path = write_bib(ad, _SAMPLE_BIB, fmt="json")
        assert path == ad / "bib.json"
        assert path.exists()

    def test_write_yaml_is_readable_by_read_bib(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        write_bib(ad, _SAMPLE_BIB, fmt="yaml")
        result = read_bib(ad)
        assert result is not None
        assert result["title"] == _SAMPLE_BIB["title"]

    def test_write_json_is_readable_by_read_bib(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        write_bib(ad, _SAMPLE_BIB, fmt="json")
        result = read_bib(ad)
        assert result is not None
        assert result["title"] == _SAMPLE_BIB["title"]

    def test_write_yaml_with_header(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        header = "# My comment header\n\n"
        write_bib(ad, _SAMPLE_BIB, fmt="yaml", yaml_header=header)
        raw = (ad / "bib.yaml").read_text(encoding="utf-8")
        assert raw.startswith("# My comment header")

    def test_write_json_is_valid_json(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        write_bib(ad, _SAMPLE_BIB, fmt="json")
        with open(ad / "bib.json", encoding="utf-8") as fh:
            parsed = json.load(fh)
        assert parsed["title"] == _SAMPLE_BIB["title"]

    def test_write_yaml_roundtrip_preserves_data(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        data = {**_SAMPLE_BIB, "authors": ["Alice Smith", "Bob Jones"]}
        write_bib(ad, data, fmt="yaml")
        result = read_bib(ad)
        assert result is not None
        assert result["authors"] == ["Alice Smith", "Bob Jones"]

    def test_write_json_roundtrip_preserves_nested(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        data = {**_SAMPLE_BIB, "_meta": {"schema_version": 2, "tool_version": "0.2.0"}}
        write_bib(ad, data, fmt="json")
        result = read_bib(ad)
        assert result is not None
        assert result["_meta"]["schema_version"] == 2

    def test_legacy_record_defaults_to_schema_version_one(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "bib.yaml", _SAMPLE_BIB)
        assert read_bib(ad)["schema_version"] == 1

    def test_write_is_atomic_existing_file_replaced(self, tmp_path):
        """Writing replaces an existing file without leaving a partial write."""
        ad = _make_analysis_dir(tmp_path)
        write_bib(ad, _SAMPLE_BIB, fmt="json")
        updated = {**_SAMPLE_BIB, "title": "Updated Title"}
        write_bib(ad, updated, fmt="json")
        result = read_bib(ad)
        assert result is not None
        assert result["title"] == "Updated Title"


# ===========================================================================
# write_distill
# ===========================================================================


class TestWriteDistill:

    def test_write_yaml_creates_yaml_file(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        path = write_distill(ad, "summary", _SAMPLE_DISTILL, fmt="yaml")
        assert path == ad / "analyses" / "summary.yaml"
        assert path.exists()

    def test_write_json_creates_json_file(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        path = write_distill(ad, "summary", _SAMPLE_DISTILL, fmt="json")
        assert path == ad / "analyses" / "summary.json"
        assert path.exists()

    def test_write_yaml_creates_analyses_dir(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        # analyses/ not created yet
        write_distill(ad, "summary", _SAMPLE_DISTILL, fmt="yaml")
        assert (ad / "analyses" / "summary.yaml").exists()

    def test_write_json_creates_analyses_dir(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        write_distill(ad, "summary", _SAMPLE_DISTILL, fmt="json")
        assert (ad / "analyses" / "summary.json").exists()

    def test_write_yaml_is_readable_by_read_distill(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        write_distill(ad, "summary", _SAMPLE_DISTILL, fmt="yaml")
        result = read_distill(ad, "summary")
        assert result is not None
        assert result["output"] == _SAMPLE_DISTILL["output"]

    def test_write_json_is_readable_by_read_distill(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        write_distill(ad, "summary", _SAMPLE_DISTILL, fmt="json")
        result = read_distill(ad, "summary")
        assert result is not None
        assert result["output"] == _SAMPLE_DISTILL["output"]

    def test_write_yaml_with_header(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        header = "# puba distill — summary\n\n"
        write_distill(ad, "summary", _SAMPLE_DISTILL, fmt="yaml", yaml_header=header)
        raw = (ad / "analyses" / "summary.yaml").read_text(encoding="utf-8")
        assert raw.startswith("# puba distill")

    def test_write_json_is_valid_json(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        write_distill(ad, "summary", _SAMPLE_DISTILL, fmt="json")
        with open(ad / "analyses" / "summary.json", encoding="utf-8") as fh:
            parsed = json.load(fh)
        assert parsed["name"] == "summary"

    def test_different_names_do_not_collide(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        d1 = {**_SAMPLE_DISTILL, "name": "summary", "output": "Summary output"}
        d2 = {**_SAMPLE_DISTILL, "name": "detail", "output": "Detail output"}
        write_distill(ad, "summary", d1, fmt="yaml")
        write_distill(ad, "detail", d2, fmt="yaml")
        r1 = read_distill(ad, "summary")
        r2 = read_distill(ad, "detail")
        assert r1 is not None and r1["output"] == "Summary output"
        assert r2 is not None and r2["output"] == "Detail output"


# ===========================================================================
# list_distill_names
# ===========================================================================


class TestListDistillNames:

    def test_empty_when_no_analyses_dir(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        assert list_distill_names(ad) == []

    def test_empty_when_analyses_dir_empty(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        (ad / "analyses").mkdir()
        assert list_distill_names(ad) == []

    def test_lists_yaml_only_names(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "analyses" / "alpha.yaml", _SAMPLE_DISTILL)
        _write_yaml(ad / "analyses" / "beta.yaml", _SAMPLE_DISTILL)
        assert list_distill_names(ad) == ["alpha", "beta"]

    def test_lists_json_only_names(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_json(ad / "analyses" / "gamma.json", _SAMPLE_DISTILL)
        assert list_distill_names(ad) == ["gamma"]

    def test_deduplicates_when_both_formats_present(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "analyses" / "summary.yaml", _SAMPLE_DISTILL)
        _write_json(ad / "analyses" / "summary.json", _SAMPLE_DISTILL)
        names = list_distill_names(ad)
        assert names.count("summary") == 1

    def test_lists_mixed_formats(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "analyses" / "old_query.yaml", _SAMPLE_DISTILL)
        _write_json(ad / "analyses" / "new_query.json", _SAMPLE_DISTILL)
        names = list_distill_names(ad)
        assert "old_query" in names
        assert "new_query" in names

    def test_ignores_dotfiles(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        (ad / "analyses").mkdir()
        (ad / "analyses" / ".gitkeep").write_text("")
        (ad / "analyses" / ".hidden.yaml").write_text("x: 1")
        assert list_distill_names(ad) == []

    def test_returns_sorted_names(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "analyses" / "zzz.yaml", _SAMPLE_DISTILL)
        _write_yaml(ad / "analyses" / "aaa.yaml", _SAMPLE_DISTILL)
        _write_yaml(ad / "analyses" / "mmm.yaml", _SAMPLE_DISTILL)
        names = list_distill_names(ad)
        assert names == sorted(names)


# ===========================================================================
# BothFormsPresentWarning — structural tests
# ===========================================================================


class TestBothFormsPresentWarning:

    def test_is_subclass_of_user_warning(self):
        assert issubclass(BothFormsPresentWarning, UserWarning)

    def test_has_json_path_and_yaml_path_attributes(self, tmp_path):
        jp = tmp_path / "bib.json"
        yp = tmp_path / "bib.yaml"
        w = BothFormsPresentWarning(jp, yp)
        assert w.json_path == jp
        assert w.yaml_path == yp

    def test_str_representation_is_informative(self, tmp_path):
        jp = tmp_path / "bib.json"
        yp = tmp_path / "bib.yaml"
        w = BothFormsPresentWarning(jp, yp)
        msg = str(w)
        assert "bib.json" in msg
        assert "bib.yaml" in msg

    def test_can_be_caught_as_user_warning(self, tmp_path):
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "bib.yaml", _SAMPLE_BIB)
        _write_json(ad / "bib.json", _SAMPLE_BIB)
        caught = []
        with warnings.catch_warnings(record=True) as w:
            warnings.simplefilter("always", UserWarning)
            read_bib(ad)
            caught = [x for x in w if issubclass(x.category, UserWarning)]
        assert len(caught) >= 1

    def test_can_be_filtered_separately(self, tmp_path):
        """Callers should be able to silence BothFormsPresentWarning independently."""
        ad = _make_analysis_dir(tmp_path)
        _write_yaml(ad / "bib.yaml", _SAMPLE_BIB)
        _write_json(ad / "bib.json", _SAMPLE_BIB)
        with warnings.catch_warnings(record=True) as caught_all:
            warnings.simplefilter("always")
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", BothFormsPresentWarning)
                read_bib(ad)
        bfp = [w for w in caught_all if issubclass(w.category, BothFormsPresentWarning)]
        assert not bfp


# ===========================================================================
# Equivalence: YAML and JSON readers return equivalent data
# ===========================================================================


class TestFormatEquivalence:
    """Both format readers must return the same logical data."""

    def test_bib_yaml_and_json_return_equivalent_data(self, tmp_path):
        ad_yaml = tmp_path / "yaml_paper.puba"
        ad_json = tmp_path / "json_paper.puba"
        ad_yaml.mkdir()
        ad_json.mkdir()

        data = {**_SAMPLE_BIB, "authors": ["Alice", "Bob"], "year": 2024}
        _write_yaml(ad_yaml / "bib.yaml", data)
        _write_json(ad_json / "bib.json", data)

        result_yaml = read_bib(ad_yaml)
        result_json = read_bib(ad_json)

        assert result_yaml is not None
        assert result_json is not None
        # Core fields must match
        assert result_yaml["title"] == result_json["title"]
        assert result_yaml["authors"] == result_json["authors"]
        assert result_yaml["year"] == result_json["year"]

    def test_distill_yaml_and_json_return_equivalent_data(self, tmp_path):
        ad_yaml = tmp_path / "yaml_paper.puba"
        ad_json = tmp_path / "json_paper.puba"
        ad_yaml.mkdir()
        ad_json.mkdir()

        data = {**_SAMPLE_DISTILL, "output": "Some output text."}
        _write_yaml(ad_yaml / "analyses" / "summary.yaml", data)
        _write_json(ad_json / "analyses" / "summary.json", data)

        result_yaml = read_distill(ad_yaml, "summary")
        result_json = read_distill(ad_json, "summary")

        assert result_yaml is not None
        assert result_json is not None
        assert result_yaml["name"] == result_json["name"]
        assert result_yaml["output"] == result_json["output"]
        assert result_yaml["scope"] == result_json["scope"]
